[env]
TERM = "xterm-256color"

[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[font]
size = 12

[font.bold]
family = "CaskaydiaCove NF"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove NF"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove NF"
style = "Italic"

[font.normal]
family = "CaskaydiaCove NF"
style = "Regular"

[window]
dynamic_title = true

[window.dimensions]
columns = 0
lines = 0

[window.position]
x = 0
y = 0

[window.padding]
x = 25
y = 15

#opacity = 1.0
#dynamic_padding = false
#decorations = "none"
# startup_mode = "SimpleFullscreen"

[scrolling]
history = 50000
multiplier = 3


[keyboard]
bindings = [
  # Copy (Ctrl+Shift+C)
  { key = "C", mods = "Control|Shift", action = "Copy" },

  # Paste (Ctrl+Shift+V)
  { key = "V", mods = "Control|Shift", action = "Paste" },

  # New window (Ctrl+Shift+N)
  { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },

  # Quit (Ctrl+Shift+Q)
  { key = "Q", mods = "Control|Shift", action = "Quit" },

  # Increase font size (Ctrl + =)
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },

  # Decrease font size (Ctrl + -)
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },

  # Reset font size (Ctrl + 0)
  { key = "Key0", mods = "Control", action = "ResetFontSize" },
	
  # Navigate skipping words
  { key = "Left",  mods = "Alt", chars = "\u001bb" },
  { key = "Right", mods = "Alt", chars = "\u001bf" }
]

[colors]
[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"

[[colors.indexed_colors]]
index = 16
color = "#ffa066"

[[colors.indexed_colors]]
index = 17
color = "#ff5d62"
